import mongoose from "mongoose";
import dotenv from "dotenv";
import Car from "../models/Car.js";

dotenv.config();

// 20 sample cars
const cars = [
  {
    name: "Toyota Corolla",
    description: "Comfortable city car",
    category: "Sedan",
    rentPrice: 50,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?toyota,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Honda Civic",
    description: "Sporty sedan with great mileage",
    category: "Sedan",
    rentPrice: 55,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?honda,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Suzuki Swift",
    description: "Compact and efficient city car",
    category: "Hatchback",
    rentPrice: 40,
    location: "Chittagong, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?suzuki,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Nissan X-Trail",
    description: "Spacious SUV for family trips",
    category: "SUV",
    rentPrice: 80,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?nissan,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Toyota RAV4",
    description: "Reliable SUV with modern features",
    category: "SUV",
    rentPrice: 85,
    location: "Sylhet, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?toyota,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Mitsubishi Outlander",
    description: "Comfortable SUV for city and off-road",
    category: "SUV",
    rentPrice: 90,
    location: "Khulna, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?mitsubishi,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "BMW 3 Series",
    description: "Luxury sedan with smooth ride",
    category: "Luxury",
    rentPrice: 120,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?bmw,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Mercedes C-Class",
    description: "Premium sedan with elegant design",
    category: "Luxury",
    rentPrice: 130,
    location: "Chittagong, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?mercedes,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Audi A4",
    description: "High performance luxury sedan",
    category: "Luxury",
    rentPrice: 125,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?audi,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Tesla Model 3",
    description: "Electric car with autopilot features",
    category: "Electric",
    rentPrice: 150,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?tesla,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Nissan Leaf",
    description: "Affordable electric hatchback",
    category: "Electric",
    rentPrice: 100,
    location: "Khulna, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?nissan,electric",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Hyundai Kona Electric",
    description: "Compact electric SUV",
    category: "Electric",
    rentPrice: 110,
    location: "Sylhet, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?hyundai,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Ford Fiesta",
    description: "Small hatchback perfect for city",
    category: "Hatchback",
    rentPrice: 45,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?ford,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Honda HR-V",
    description: "Compact SUV with comfort",
    category: "SUV",
    rentPrice: 75,
    location: "Chittagong, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?honda,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Toyota Prius",
    description: "Hybrid sedan with excellent mileage",
    category: "Sedan",
    rentPrice: 60,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?toyota,hybrid",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Kia Sportage",
    description: "Mid-size SUV with modern design",
    category: "SUV",
    rentPrice: 80,
    location: "Sylhet, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?kia,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Volkswagen Golf",
    description: "Hatchback with sporty feel",
    category: "Hatchback",
    rentPrice: 50,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?volkswagen,car",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Mazda CX-5",
    description: "Reliable SUV with stylish look",
    category: "SUV",
    rentPrice: 85,
    location: "Khulna, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?mazda,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "BMW X5",
    description: "Luxury SUV for family and travel",
    category: "Luxury",
    rentPrice: 140,
    location: "Dhaka, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?bmw,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
  {
    name: "Audi Q5",
    description: "Premium SUV with comfort and style",
    category: "Luxury",
    rentPrice: 145,
    location: "Chittagong, Bangladesh",
    imageUrl: "https://source.unsplash.com/300x200/?audi,suv",
    providerName: "Admin",
    providerEmail: "admin@example.com",
    status: "Available",
  },
];

const seedCars = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    await Car.deleteMany(); // Optional: clear existing cars
    await Car.insertMany(cars);

    console.log("✅ 20 cars seeded successfully");
    process.exit();
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
};

seedCars();
